/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author devmat
 */
public class CadFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public CadFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        campoEndereco = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionario = new javax.swing.JTable();
        boxCargo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        butaoCadastrar = new javax.swing.JToggleButton();
        butaoOcultar = new javax.swing.JButton();
        campoSenha = new javax.swing.JPasswordField();
        campoCpf = new javax.swing.JFormattedTextField();
        cadFunc = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoPesquisa = new javax.swing.JTextField();
        tabelaFuncDel = new javax.swing.JScrollPane();
        tabelaFuncionario2 = new javax.swing.JTable();
        bdelet = new javax.swing.JToggleButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CARGO:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 60, 20));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SENHA:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, 20));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CPF:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 20));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("TELEFONE:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, 20));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ENDEREÇO:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 20));

        campoTelefone.setBackground(new java.awt.Color(255, 255, 255));
        campoTelefone.setForeground(new java.awt.Color(0, 0, 0));
        campoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefoneActionPerformed(evt);
            }
        });
        jPanel2.add(campoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 250, 35));

        campoNome.setBackground(new java.awt.Color(255, 255, 255));
        campoNome.setForeground(new java.awt.Color(0, 0, 0));
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        jPanel2.add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 35));

        campoEndereco.setBackground(new java.awt.Color(255, 255, 255));
        campoEndereco.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(campoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 250, 35));

        tabelaFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        tabelaFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "CPF", "TELEFONE", "ENDEREÇO", "DEPARTAMENTO", "SENHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaFuncionario);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 690, 150));

        boxCargo.setBackground(new java.awt.Color(255, 255, 255));
        boxCargo.setForeground(new java.awt.Color(0, 0, 0));
        boxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Síndico", "Porteiro", "Guarda", "Zelador", "Jardineiro", " " }));
        jPanel2.add(boxCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 210, 35));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("NOME:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));

        butaoCadastrar.setBackground(new java.awt.Color(255, 204, 0));
        butaoCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        butaoCadastrar.setText("CADASTRAR");
        butaoCadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        butaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(butaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 110, 40));

        butaoOcultar.setBackground(new java.awt.Color(187, 187, 187));
        butaoOcultar.setBorder(null);
        jPanel2.add(butaoOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 50, 35));

        campoSenha.setBackground(new java.awt.Color(255, 255, 255));
        campoSenha.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 160, 35));

        campoCpf.setBackground(new java.awt.Color(255, 255, 255));
        campoCpf.setForeground(new java.awt.Color(0, 0, 0));
        try {
            campoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(campoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, 35));

        jTabbedPane1.addTab("Cadastrar", jPanel2);

        cadFunc.setBackground(new java.awt.Color(255, 204, 0));
        cadFunc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("PESQUISAR");
        cadFunc.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 30));

        campoPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        campoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesquisaActionPerformed(evt);
            }
        });
        cadFunc.add(campoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 310, 35));

        tabelaFuncionario2.setBackground(new java.awt.Color(255, 255, 255));
        tabelaFuncionario2.setForeground(new java.awt.Color(0, 0, 0));
        tabelaFuncionario2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NOME", "CPF", "TELEFONE", "ENDEREÇO", "DEPARTAMENTO", "SENHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFuncDel.setViewportView(tabelaFuncionario2);

        cadFunc.add(tabelaFuncDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 690, 310));

        bdelet.setBackground(new java.awt.Color(255, 204, 0));
        bdelet.setForeground(new java.awt.Color(0, 0, 0));
        bdelet.setText("Deletar");
        bdelet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bdelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeletActionPerformed(evt);
            }
        });
        cadFunc.add(bdelet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 110, 30));

        jTabbedPane1.addTab("Deletar", cadFunc);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, -5, 720, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesquisaActionPerformed

    private void butaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butaoCadastrarActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void bdeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdeletActionPerformed

    private void campoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bdelet;
    private javax.swing.JComboBox<String> boxCargo;
    private javax.swing.JToggleButton butaoCadastrar;
    private javax.swing.JButton butaoOcultar;
    private javax.swing.JPanel cadFunc;
    private javax.swing.JFormattedTextField campoCpf;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane tabelaFuncDel;
    private javax.swing.JTable tabelaFuncionario;
    private javax.swing.JTable tabelaFuncionario2;
    // End of variables declaration//GEN-END:variables
}
