/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author devmat
 */
public class TelaAtividade extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrame
     */
    public TelaAtividade() {
        initComponents();
        
       
        bExcluir.setVisible(false);
        bConcluida.setVisible(false);
        
    }
    
    /*private void listarAtividadesNaTela() {
    painelAtividades.removeAll(); // limpa antes de atualizar

    controller.AtividadeController controller = new controller.AtividadeController();
    java.util.List<model.Atividade> lista = controller.listarAtividade(); // chama o DAO

    if (lista != null) {
        for (model.Atividade a : lista) {
            javax.swing.JTextArea area = new javax.swing.JTextArea();
            area.setText("Nome: " + a.getNome()
                        + "\nDescrição: " + a.getDescricao()
                        + "\nPrazo: " + a.getDatas()
                        + "\nStatus: " + a.getStatu());
            area.setEditable(false);
            area.setBackground(new java.awt.Color(255, 255, 204));
            area.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
            area.setLineWrap(true);
            area.setWrapStyleWord(true);
            area.setMaximumSize(new java.awt.Dimension(650, 80)); // ajusta largura

            painelAtividades.add(area);
            painelAtividades.add(javax.swing.Box.createVerticalStrut(10));
        }

        painelAtividades.revalidate();
        painelAtividades.repaint();
    }
}*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bCadastrar = new javax.swing.JButton();
        bAtvConc = new javax.swing.JButton();
        bConcluida = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bCadastrar.setBackground(new java.awt.Color(255, 204, 0));
        bCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        bCadastrar.setText("Cadastrar");
        bCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(bCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 130, 40));

        bAtvConc.setBackground(new java.awt.Color(255, 204, 0));
        bAtvConc.setForeground(new java.awt.Color(0, 0, 0));
        bAtvConc.setText("Atividades Concluídas");
        jPanel1.add(bAtvConc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 200, 40));

        bConcluida.setBackground(new java.awt.Color(255, 204, 0));
        bConcluida.setForeground(new java.awt.Color(0, 0, 0));
        bConcluida.setText("Concluída");
        bConcluida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConcluidaActionPerformed(evt);
            }
        });
        jPanel1.add(bConcluida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 130, 40));

        bExcluir.setBackground(new java.awt.Color(255, 204, 0));
        bExcluir.setForeground(new java.awt.Color(0, 0, 0));
        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(bExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarActionPerformed
        // TODO add your handling code here:
         CadAtv cadastro = new CadAtv ();
        cadastro.setVisible(true);
    }//GEN-LAST:event_bCadastrarActionPerformed

    private void bConcluidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConcluidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bConcluidaActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtvConc;
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton bConcluida;
    private javax.swing.JButton bExcluir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
