/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author devmat
 */
public class TelaCadastroUnidade extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroUnidade
     */
    public TelaCadastroUnidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        tipo = new javax.swing.JLabel();
        campoTipo = new javax.swing.JComboBox<>();
        numero = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        bloco = new javax.swing.JLabel();
        campoBloco = new javax.swing.JTextField();
        capacidade = new javax.swing.JLabel();
        campoCapacidade = new javax.swing.JTextField();
        dimensoes = new javax.swing.JLabel();
        campoDimensoes = new javax.swing.JTextField();
        descicao = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JTextField();
        nomeChave = new javax.swing.JLabel();
        campoNomeChave = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUnidade = new javax.swing.JTable();
        campoPesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        butaoDeletar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 0));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome.setForeground(new java.awt.Color(0, 0, 0));
        nome.setText("NOME:");
        jPanel1.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, -1));

        campoNome.setBackground(new java.awt.Color(255, 255, 255));
        campoNome.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 220, 35));

        tipo.setForeground(new java.awt.Color(0, 0, 0));
        tipo.setText("TIPO:");
        jPanel1.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 62, -1));

        campoTipo.setBackground(new java.awt.Color(255, 255, 255));
        campoTipo.setForeground(new java.awt.Color(0, 0, 0));
        campoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Espaço De Evento", "Outros", " " }));
        jPanel1.add(campoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 35));

        numero.setForeground(new java.awt.Color(0, 0, 0));
        numero.setText("NUMERO:");
        jPanel1.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 56, -1));

        campoNumero.setBackground(new java.awt.Color(255, 255, 255));
        campoNumero.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, 35));

        bloco.setForeground(new java.awt.Color(0, 0, 0));
        bloco.setText("BLOCO:");
        jPanel1.add(bloco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 64, -1));

        campoBloco.setBackground(new java.awt.Color(255, 255, 255));
        campoBloco.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoBloco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 220, 35));

        capacidade.setForeground(new java.awt.Color(0, 0, 0));
        capacidade.setText("CAPACIDADE:");
        jPanel1.add(capacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 84, -1));

        campoCapacidade.setBackground(new java.awt.Color(255, 255, 255));
        campoCapacidade.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoCapacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 220, 35));

        dimensoes.setForeground(new java.awt.Color(0, 0, 0));
        dimensoes.setText("DIMENSÕES");
        jPanel1.add(dimensoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 80, -1));

        campoDimensoes.setBackground(new java.awt.Color(255, 255, 255));
        campoDimensoes.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoDimensoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 220, 35));

        descicao.setForeground(new java.awt.Color(0, 0, 0));
        descicao.setText("DESCRIÇÃO");
        jPanel1.add(descicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 103, -1));

        campoDescricao.setBackground(new java.awt.Color(255, 255, 255));
        campoDescricao.setForeground(new java.awt.Color(0, 0, 0));
        campoDescricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(campoDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 220, 110));

        nomeChave.setForeground(new java.awt.Color(0, 0, 0));
        nomeChave.setText("NOME CHAVE:");
        jPanel1.add(nomeChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 90, -1));

        campoNomeChave.setBackground(new java.awt.Color(255, 255, 255));
        campoNomeChave.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoNomeChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 120, 35));

        jToggleButton1.setText("Cadastrar");
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 125, 57));

        jTabbedPane1.addTab("Cadastrar", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaUnidade.setBackground(new java.awt.Color(255, 255, 255));
        listaUnidade.setForeground(new java.awt.Color(0, 0, 0));
        listaUnidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", ""},
                {"", "", "", "", ""},
                {"", "", "", "", null},
                {"", "", null, "", ""},
                {"", "", "", "", null},
                {null, "", "", "", null},
                {"", null, "", null, ""},
                {null, null, null, null, ""},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Numero", "Bloco", "Tipo", "Capacidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaUnidade.setSelectionBackground(new java.awt.Color(255, 255, 255));
        listaUnidade.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(listaUnidade);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 706, 285));

        campoPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        campoPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(campoPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, 380, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PESQUISAR:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 87, -1));

        butaoDeletar.setBackground(new java.awt.Color(255, 204, 0));
        butaoDeletar.setForeground(new java.awt.Color(0, 0, 0));
        butaoDeletar.setText("DELETAR");
        butaoDeletar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(butaoDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 85, 38));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Deletar", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloco;
    private javax.swing.JButton butaoDeletar;
    private javax.swing.JTextField campoBloco;
    private javax.swing.JTextField campoCapacidade;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoDimensoes;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeChave;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoPesquisar;
    private javax.swing.JComboBox<String> campoTipo;
    private javax.swing.JLabel capacidade;
    private javax.swing.JLabel descicao;
    private javax.swing.JLabel dimensoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable listaUnidade;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel nomeChave;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
}
