/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author devmat
 */
public class telaRelatorioReserva extends javax.swing.JInternalFrame {

    /**
     * Creates new form RelatorioReserva
     */
    public telaRelatorioReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRelatório = new javax.swing.JTable();
        butaoBaixarRelatorio = new javax.swing.JToggleButton();
        relatoriomensal = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaRelatório.setBackground(new java.awt.Color(255, 255, 255));
        tabelaRelatório.setForeground(new java.awt.Color(0, 0, 0));
        tabelaRelatório.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Funcionário Entrega", "Entrega", "Func Devolução", "Devolução", "Nome do Morador", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelaRelatório);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 690, 330));

        butaoBaixarRelatorio.setBackground(new java.awt.Color(255, 204, 0));
        butaoBaixarRelatorio.setForeground(new java.awt.Color(0, 0, 0));
        butaoBaixarRelatorio.setText("Baixar Relatório");
        butaoBaixarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoBaixarRelatorioActionPerformed(evt);
            }
        });
        jPanel1.add(butaoBaixarRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 130, 30));

        relatoriomensal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        relatoriomensal.setForeground(new java.awt.Color(0, 0, 0));
        relatoriomensal.setText("RELATÓRIO MENSAL");
        jPanel1.add(relatoriomensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 727, 457));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butaoBaixarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoBaixarRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butaoBaixarRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton butaoBaixarRelatorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel relatoriomensal;
    private javax.swing.JTable tabelaRelatório;
    // End of variables declaration//GEN-END:variables
}
