/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Funcionario;

/**
 *
 * @author devmat
 */
public class TelaHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    Funcionario use;
    
    public TelaHome(String departamento , Funcionario funcionario) {
        initComponents();
        use = funcionario;
        
          // Verifica o departamento do funcionário e ajusta a interface
        if (departamento.equals("Síndico")){
            // Adiciona funcionalidades exclusivas para o Síndico
            BuCadastro.setEnabled(true); // Exemplo, permitir cadastro
            buRelatorio.setEnabled(true); // Exemplo, permitir relatórios
            buFinanceiro.setEnabled(true); // Exemplo, permitir acesso financeiro
            buReserva.setEnabled(true); // Exemplo, permitir reservas
            // Adicione mais botões se necessário
     
        } else if (departamento.equals("Porteiro")) {
            // Adiciona funcionalidades exclusivas para o Porteiro
            BuCadastro.setEnabled(false); // Exemplo, desabilitar cadastro
            buRelatorio.setEnabled(false); // Exemplo, desabilitar relatórios
            buFinanceiro.setEnabled(false); // Exemplo, desabilitar financeiro
            buReserva.setEnabled(true); // Exemplo, permitir reservas
            // Adicione mais configurações para o porteiro
 
    }//fim do else
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BuCadastro = new javax.swing.JButton();
        buReserva = new javax.swing.JButton();
        buRelatorio = new javax.swing.JButton();
        buConfig = new javax.swing.JButton();
        buFinanceiro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        BuCadastro.setBackground(new java.awt.Color(255, 153, 0));
        BuCadastro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BuCadastro.setForeground(new java.awt.Color(0, 0, 0));
        BuCadastro.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\usuarios-alt.png")); // NOI18N
        BuCadastro.setText("CADASTRO");
        BuCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuCadastroActionPerformed(evt);
            }
        });

        buReserva.setBackground(new java.awt.Color(255, 153, 0));
        buReserva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buReserva.setForeground(new java.awt.Color(0, 0, 0));
        buReserva.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\calendario.png")); // NOI18N
        buReserva.setText("RESERVA");
        buReserva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buRelatorio.setBackground(new java.awt.Color(255, 153, 0));
        buRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buRelatorio.setForeground(new java.awt.Color(0, 0, 0));
        buRelatorio.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\estatisticas.png")); // NOI18N
        buRelatorio.setText("RELATORIO");
        buRelatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buConfig.setBackground(new java.awt.Color(255, 153, 0));
        buConfig.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buConfig.setForeground(new java.awt.Color(0, 0, 0));
        buConfig.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\config.png")); // NOI18N
        buConfig.setText("CONFIGURAÇÕES");
        buConfig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buFinanceiro.setBackground(new java.awt.Color(255, 153, 0));
        buFinanceiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buFinanceiro.setForeground(new java.awt.Color(0, 0, 0));
        buFinanceiro.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Downloads\\dolar.png")); // NOI18N
        buFinanceiro.setText("FINANCEIRO");
        buFinanceiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(BuCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(buReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(buRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(buFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(buConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 480, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuCadastroActionPerformed
        
        TelaCadastro cadastro = new TelaCadastro(use.getDepartamento(),use);
            cadastro.setVisible(true);
            
            dispose();
    }//GEN-LAST:event_BuCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Funcionario use = null;
                String departamento = null;
                new TelaHome(departamento,use).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuCadastro;
    private javax.swing.JButton buConfig;
    private javax.swing.JButton buFinanceiro;
    private javax.swing.JButton buRelatorio;
    private javax.swing.JButton buReserva;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
