/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import com.itextpdf.text.Document;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import controller.ContResController;
import java.awt.Desktop;
import java.io.File;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.RelatorioReserva;

/**
 *
 * @author devmat
 */
public class telaRelatorioReserva extends javax.swing.JInternalFrame {

    /**
     * Creates new form RelatorioReserva
     */
    public telaRelatorioReserva() {
        initComponents();
        ListagemRelatorio();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRelatorio = new javax.swing.JTable();
        butaoBaixarRelatorio = new javax.swing.JToggleButton();
        relatoriomensal = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        tabelaRelatorio.setForeground(new java.awt.Color(0, 0, 0));
        tabelaRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Funcionário Entrega", "Entrega", "Func Devolução", "Devolução", "Nome do Morador"
            }
        ));
        jScrollPane1.setViewportView(tabelaRelatorio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 690, 330));

        butaoBaixarRelatorio.setBackground(new java.awt.Color(255, 204, 0));
        butaoBaixarRelatorio.setForeground(new java.awt.Color(0, 0, 0));
        butaoBaixarRelatorio.setText("Baixar Relatório");
        butaoBaixarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoBaixarRelatorioActionPerformed(evt);
            }
        });
        jPanel1.add(butaoBaixarRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 130, 30));

        relatoriomensal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        relatoriomensal.setForeground(new java.awt.Color(0, 0, 0));
        relatoriomensal.setText("RELATÓRIO MENSAL");
        jPanel1.add(relatoriomensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 727, 457));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ListagemRelatorio(){
        //cria um objeto de vendasController
        ContResController controller = new  ContResController();
        //capturando a lista de relatório de vendas
        List<RelatorioReserva> lista = controller.listarRelatorios();
        
        //modelo padrão de tabela
       DefaultTableModel modeloTabela = (DefaultTableModel)tabelaRelatorio.getModel();
        
       //Limpando a tabela antes de adicionar nobvos dados
       modeloTabela.setRowCount(0);
       
       //verificar se a lista esta vazia
       if(lista !=null && !lista.isEmpty()){
           for (RelatorioReserva reserva : lista){
               Object[] linha = {
                   reserva.getFunc_entrega(),
                   reserva.getData_entrega(),
                   reserva.getFunc_devolucao(),
                   reserva.getData_devolucao(),
                   reserva.getMorador(),
   
               };//fim do objeto linha
               modeloTabela.addRow(linha);
               
           }//fim do for
       }else{
           JOptionPane.showMessageDialog(null,"Não existem vendas!");
       }//fim do else
    
    }
    
    
    
    private void butaoBaixarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoBaixarRelatorioActionPerformed
        // TODO add your handling code here:
        String pdfPath = "RelatorioDeReservas.pdf";
        
        try{
            
            //criando documento pdf
            Document documento = new Document();
            PdfWriter.getInstance(documento, new java.io.FileOutputStream(pdfPath));
            
            //abrir pdf
            documento.open();
            
            //Criando tabela no pdf
            //getColumn captura a quantidade do colunas da tabelaVendas
            int  colunas = tabelaRelatorio.getColumnCount() ;
            //definindo a nossa tabela dentro do pdf
            PdfPTable tabela = new PdfPTable(colunas);
            //definindo a escala da tabela 100%, 80%, 50% 
            tabela.setWidthPercentage(100);
            
            //adicionando o nome das colunas na tabela do pdf
            for(int i=0 ; i< colunas; i++){
                tabela.addCell(new Phrase(tabelaRelatorio.getColumnName(i)));
            }//fim do laço de repetição FOR
            
            //adicionando os dados na tabela pdf 
            DefaultTableModel modeloTabela = (DefaultTableModel) tabelaRelatorio.getModel();
            //usnado laço de repetição para inserir os dados 
            for(int l = 0; l < modeloTabela.getRowCount(); l ++){
                for (int c = 0; c < modeloTabela.getColumnCount(); c++ ){
                    //Adicionando os dados e jogando em um objeto 
                    Object valorcelula = modeloTabela.getValueAt(l,c);
                tabela.addCell(valorcelula != null ? valorcelula.toString():"");
                
            }//fim do 2° for     
            }//fim do 1° for
            
            //adicionando a tabela dentro do pdf
            documento.add(tabela);
            
            // fechando o documento 
            documento.close();
            
            //mensagem de sucesso
            JOptionPane.showMessageDialog(this,"PDF GERADO COM SUCESSO");
            
            //abrir o pdf automaticamente
            File pdffile = new File(pdfPath);
            //se pdf existir 
            if(pdffile.exists()){
                
            if(Desktop.isDesktopSupported()){
                //achou o aplicativo que abre o pdf então
                //abre o arquivo dentro do aplicativo
                Desktop.getDesktop().open(pdffile);
            }
            else{
                JOptionPane.showMessageDialog(this,"Nenhum aplicativo suporta o PDF!");
            }//fim do else
            }//fim do if
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Não fgoi possível gerar PDF!" +e);
        }//fim do trycatch
                                         
    }//GEN-LAST:event_butaoBaixarRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton butaoBaixarRelatorio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel relatoriomensal;
    private javax.swing.JTable tabelaRelatorio;
    // End of variables declaration//GEN-END:variables
}
