/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

/**
 *
 * @author devmat
 */
public class TelaEntradaSaida extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaEntradaSaida
     */
    public TelaEntradaSaida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelEntrada = new javax.swing.JPanel();
        campoNomeMorador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaMorador = new javax.swing.JTable();
        bPermitirEntrada = new javax.swing.JButton();
        bCadastrarVisitante = new javax.swing.JButton();
        PanelSaida = new javax.swing.JPanel();
        campoNomeVistante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVisitante = new javax.swing.JTable();
        bPermitirSaida = new javax.swing.JButton();

        PanelEntrada.setBackground(new java.awt.Color(255, 204, 0));

        campoNomeMorador.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MORADOR:");

        tabelaMorador.setBackground(new java.awt.Color(255, 255, 255));
        tabelaMorador.setForeground(new java.awt.Color(0, 0, 0));
        tabelaMorador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CASA", "NOME", "CPF", "EMAIL", "DATA NASCIMENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaMorador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMoradorMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelaMorador);

        bPermitirEntrada.setForeground(new java.awt.Color(255, 255, 255));
        bPermitirEntrada.setText("PERMITIR ENTRADA");

        bCadastrarVisitante.setForeground(new java.awt.Color(255, 255, 255));
        bCadastrarVisitante.setText("CADASTRAR VISITANTE");

        javax.swing.GroupLayout PanelEntradaLayout = new javax.swing.GroupLayout(PanelEntrada);
        PanelEntrada.setLayout(PanelEntradaLayout);
        PanelEntradaLayout.setHorizontalGroup(
            PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addGroup(PanelEntradaLayout.createSequentialGroup()
                        .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNomeMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEntradaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bCadastrarVisitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bPermitirEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(275, 275, 275))
        );
        PanelEntradaLayout.setVerticalGroup(
            PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntradaLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(bPermitirEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCadastrarVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Entrada", PanelEntrada);

        PanelSaida.setBackground(new java.awt.Color(255, 204, 0));

        campoNomeVistante.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NOME VISITANTE:");

        tabelaVisitante.setBackground(new java.awt.Color(255, 255, 255));
        tabelaVisitante.setForeground(new java.awt.Color(0, 0, 0));
        tabelaVisitante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaVisitante);

        bPermitirSaida.setForeground(new java.awt.Color(255, 255, 255));
        bPermitirSaida.setText("PERMITIR SAIDA");

        javax.swing.GroupLayout PanelSaidaLayout = new javax.swing.GroupLayout(PanelSaida);
        PanelSaida.setLayout(PanelSaidaLayout);
        PanelSaidaLayout.setHorizontalGroup(
            PanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addGroup(PanelSaidaLayout.createSequentialGroup()
                        .addGroup(PanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(campoNomeVistante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelSaidaLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(bPermitirSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSaidaLayout.setVerticalGroup(
            PanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeVistante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(bPermitirSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Saida", PanelSaida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMoradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMoradorMouseClicked
        // TODO add your handling code here:
        /*int linhaSelecionada = tabelaMorador.getSelectedRow();

        // Verificando se alguma linha foi selecionada
        if (linhaSelecionada >= 0) {
            // Definir modelo default para a tabela
            DefaultTableModel modeloTabela = (DefaultTableModel) tabelaMorador.getModel();

            // Verificando se os valores não são nulos antes de usar toString()
            idMorador = modeloTabela.getValueAt(linhaSelecionada, 0) != null
            ? Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 0).toString())
            : 0;  // Valor padrão para idMorador (caso seja nulo)

            idUnidade = modeloTabela.getValueAt(linhaSelecionada, 1) != null
            ? Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 1).toString())
            : 0;  // Valor padrão para idUnidade (caso seja nulo)

            campoNome.setText(modeloTabela.getValueAt(linhaSelecionada, 2) != null
                ? modeloTabela.getValueAt(linhaSelecionada, 2).toString()
                : "N/A");  // Valor padrão para Nome (caso seja nulo)

            campoCpf.setText(modeloTabela.getValueAt(linhaSelecionada, 3) != null
                ? modeloTabela.getValueAt(linhaSelecionada, 3).toString()
                : "N/A");  // Valor padrão para CPF (caso seja nulo)

            campoEmail.setText(modeloTabela.getValueAt(linhaSelecionada, 4) != null
                ? modeloTabela.getValueAt(linhaSelecionada, 4).toString()
                : "N/A");  // Valor padrão para Email (caso seja nulo)

            campNascimento.setText(modeloTabela.getValueAt(linhaSelecionada, 5) != null
                ? modeloTabela.getValueAt(linhaSelecionada, 5).toString()
                : "N/A");  // Valor padrão para Data de Nascimento (caso seja nulo)
        } // fim do if*/
    }//GEN-LAST:event_tabelaMoradorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEntrada;
    private javax.swing.JPanel PanelSaida;
    private javax.swing.JButton bCadastrarVisitante;
    private javax.swing.JButton bPermitirEntrada;
    private javax.swing.JButton bPermitirSaida;
    private javax.swing.JTextField campoNomeMorador;
    private javax.swing.JTextField campoNomeVistante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaMorador;
    private javax.swing.JTable tabelaVisitante;
    // End of variables declaration//GEN-END:variables
}
